apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: llm-ops-server-cluster-main
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  data:
    - secretKey: llm-ops-secret
      remoteRef:
        key: "/realtime-streaming/ch/smartnews-main-dev/default_sa"